# Generated by Django 3.2.9 on 2021-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(max_length=255)),
                ('snippet_type', models.CharField(choices=[('adsense', 'Google adsense')], default='adsense', max_length=255)),
            ],
        ),
    ]
