# Generated by Django 3.2.9 on 2021-11-06 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seed',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='seed',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
