# Generated by Django 3.2.9 on 2021-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_latest_activity', models.DateTimeField(auto_now=True)),
                ('latest_activity_hash', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('browser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_count', models.IntegerField(default=0)),
            ],
        ),
    ]
