# Generated by Django 3.2.9 on 2021-11-05 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_unidecoded', models.CharField(max_length=255)),
                ('master_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_placeholder', models.BooleanField(default=False)),
                ('content_type', models.IntegerField(choices=[(0, 'Header'), (1, 'Title'), (2, 'Paragraph'), (3, 'Image'), (4, 'List'), (5, 'Content'), (6, 'Navigation'), (7, 'Searchbar'), (7, 'Footer')], default=0)),
                ('order', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.pagecontent')),
            ],
        ),
    ]
