# Generated by Django 3.2.9 on 2021-11-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('content', '0003_auto_20211105_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='styles.style'),
        ),
    ]
