# Generated by Django 3.2.9 on 2021-11-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20211105_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='external_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
