# Generated by Django 3.2.9 on 2021-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_pagecontent_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('html_tag', models.CharField(choices=[('title', 'Title'), ('meta', 'Meta tag'), ('link', 'Link tag')], max_length=255)),
            ],
        ),
    ]
