# Generated by Django 3.2.9 on 2021-11-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='MetaItem',
        ),
    ]
