# Generated by Django 3.2.9 on 2021-11-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20211106_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.meta'),
        ),
    ]
