# Generated by Django 3.2.9 on 2021-11-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('margin', 'margin'), ('padding', 'padding'), ('font-family', 'font-family'), ('font-size', 'font-size'), ('border', 'border'), ('box-sizing', 'box-sizing'), ('background', 'background'), ('color', 'color')], max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('px', 'Pixels'), ('em', 'Line-width'), ('vw', 'Viewport-width'), ('vh', 'Viewport-height'), ('%', 'Percent')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extends', models.ManyToManyField(blank=True, null=True, related_name='_styles_style_extends_+', to='styles.Style')),
            ],
        ),
    ]
