# Generated by Django 3.2.9 on 2021-11-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_attribute_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, choices=[('px', 'Pixels'), ('em', 'Line-width'), ('vw', 'Viewport-width'), ('vh', 'Viewport-height'), ('%', 'Percent')], max_length=255, null=True),
        ),
    ]
